# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-27 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20190427_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='hbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.BookInfo', verbose_name='一对多关联图书表'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hcontent',
            field=models.CharField(max_length=100, verbose_name='英雄描述信息'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hgender',
            field=models.BooleanField(default=True, verbose_name='英雄性别'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hname',
            field=models.CharField(max_length=20, verbose_name='英雄姓名'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
