# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-27 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20190427_1117'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookInfo',
        ),
        migrations.AlterModelTable(
            name='heroinfo',
            table='heroInfo',
        ),
    ]
