# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-27 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_auto_20190427_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='btitle',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='bitle',
            field=models.CharField(blank=True, max_length=20, verbose_name='图书名称'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='bpub_date',
            field=models.DateField(null=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hname',
            field=models.CharField(max_length=20, unique=True, verbose_name='英雄姓名'),
        ),
    ]
